[build]
  command = "npm run build"
  publish = 
    "out"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
